### PR TITLE
Change characterID to playerUID on object publish

### PR DESCRIPTION
**Pull request by gnif**
This update changes characerID of type int to playerUID of type string as this is needed for vault storage. This also fixes some of the build issues with compiling on VC2010 Express.

If this patch is applied the database schema needs to be updated, as does the dayz client code, where all instances of dayz_characterID for call 308 need to be changed to dayz_playerUID.

Please see here for the client changes:
https://github.com/vbawol/DayZ-Epoch/pull/350

Please note that this also requires a schema change
ALTER TABLE `Object_DATA` MODIFY COLUMN `CharacterID` VARCHAR(20) NOT NULL DEFAULT '0'

As a side effect this also fixes the issue where players can not pack their own tents after they die.

### CODE REVIEW

**Comment by kikyou2** [comment]
Then you also have to edit the fn_selfActions.sqf

if(cursorTarget isKindOf "TentStorage" and _canDo and _ownerID == dayz_characterID) then {

to I think this one

if(cursorTarget isKindOf "TentStorage" and _canDo and _ownerID == dayz_characterID or _ownerID == dayz_playerUID) then {

Otherwise the pack tent feature will no longer work.

**Comment by gnif** [comment]
@kikyou2: You are correct, but no need to check against characterID as the ownerID will never be a characterID any more.

**Comment by kikyou2** [comment]
But for all old Serverowner it should be added, cause the old tents which are set up are in the database with characterID. So the old tents wouldn't recognize the owner even if they have the right characterID.

Thats why I didn't replaced it.

**Comment by gnif** [comment]
@kikyou2: The better fix then would be to write a query that fixed the database records when admins migrate to the new version:

``` SQL
 CREATE TABLE `Object_DATA2` (
  `ObjectID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `ObjectUID` bigint(24) NOT NULL DEFAULT '0',
  `Instance` int(11) unsigned NOT NULL,
  `Classname` varchar(50) DEFAULT NULL,
  `Datestamp` datetime NOT NULL,
  `CharacterID` varchar(20) NOT NULL DEFAULT '0',
  `Worldspace` varchar(128) NOT NULL DEFAULT '[]',
  `Inventory` longtext,
  `Hitpoints` varchar(512) NOT NULL DEFAULT '[]',
  `Fuel` double(13,5) NOT NULL DEFAULT '1.00000',
  `Damage` double(13,5) NOT NULL DEFAULT '0.00000',
  PRIMARY KEY (`ObjectID`),
  KEY `ObjectUID` (`ObjectUID`) USING BTREE,
  KEY `Instance` (`Instance`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

INSERT INTO `Object_DATA2`
  SELECT
    A.`ObjectID`,
    A.`ObjectUID`,
    A.`Instance`,
    A.`Classname`,
    A.`Datestamp`,
    B.`PlayerUID` AS 'CharacterID',
    A.`Worldspace,
    A.`Inventory`,
    A.`Hitpoints`,
    A.`Fuel`,
    A.`Damage`
  FROM
    `Object_DATA` A,
    `Character_DATA` B
  WHERE
    B.`CharacterID` = A.`CharacterID`
UNION
  SELECT
    *
  FROM
    `Object_DATA`
  WHERE
    `CharacterID` NOT IN (
      SELECT
        `CharacterID`
      FROM
        `Character_DATA`
    );

DROP TABLE `Object_DATA`;
RENAME `Object_DATA2` TO `Object_DATA`;
```

**Comment by kikyou2** [comment]
Yes you're right. Damn I posted it on the false thread >.<

**Comment by gnif** [comment]
@vbawol: Any chance of getting this applied and released? This is affecting quite a few of my friends who would like to play Epoch.

**Comment by vbawol** [comment]
In 1.0.1 we will have a new way, that will fix this without changes to the dll. I think you will like it, stay tuned...

**Comment by gnif** [comment]
@vbawol: Why do you want to continue to work around old code? The DLL needs a heap of new features, and I planned to add a few more calls to save/load friendly tags which will be further changes. If compiling the DLL is an issue, I would be happy to do it as I have a working development environment.

**Comment by vbawol** [comment]
Its not that I am working around it I am making it work like I intended. Vehicles, or vaults will no longer be tied to your CharID or UID. Vaults will now use a 4 digit pin and vehicles will now have keys. However, there are other reasons to update the dll to at least the latest from Rajkosto https://github.com/rajkosto/hive. The last time I looked his version does not have the 999 998 custom sql support, so we may need to look further for that. I do not have my development environment setup right now as I compiled this several months ago. If you would like to further the development of the dll I and everyone else would appreciate it.

**Comment by vbawol** [comment]
new hive dll with custom

**Pull request closed without merging**
